from reta_mojo.legacy_libreta_prompt import bootstrap_legacy_libreta_prompt


def main() raises:
    var facade = bootstrap_legacy_libreta_prompt()
    print("mainParas_len=" + String(len(facade.mainParas)))
    print("mainParas_first=" + facade.mainParas[0])
    print("mainParas_last=" + facade.mainParas[len(facade.mainParas) - 1])
    print("spalten_len=" + String(len(facade.spalten)))
    print("eigsN_len=" + String(len(facade.eigsN)))
    print("eigsR_len=" + String(len(facade.eigsR)))
    print("spaltenDict_len=" + String(len(facade.spaltenDict)))
    print("zeilenTypen_len=" + String(len(facade.zeilenTypen)))
    print("zeilenZeit_len=" + String(len(facade.zeilenZeit)))
    print("zeilenTypenB_len=" + String(len(facade.zeilenTypenB)))
    print("ausgabeParas_len=" + String(len(facade.ausgabeParas)))
    print("kombiMainParas_len=" + String(len(facade.kombiMainParas)))
    print("zeilenParas_len=" + String(len(facade.zeilenParas)))
    print("hauptForNeben_len=" + String(len(facade.hauptForNeben)))
    print("notParameterValues_len=" + String(len(facade.notParameterValues)))
    print("hauptForNebenSet_len=" + String(len(facade.hauptForNebenSet)))
    print("ausgabeArt_len=" + String(len(facade.ausgabeArt)))
    print("gebrochenErlaubteZahlen_len=" + String(len(facade.gebrochenErlaubteZahlen)))
    print("missingWahl15Values_len=" + String(len(facade.missingWahl15Values)))
    print("befehle_len=" + String(len(facade.befehle)))
    print("befehle2_len=" + String(len(facade.befehle2)))
    print("wahl15_len=" + String(len(facade.wahl15)))
    print("wahl16_len=" + String(len(facade.wahl16)))
    print("wahl15_first_key=" + facade.wahl15[0].key)
    print("wahl16_first_key=" + facade.wahl16[0].key)
    print("runtime_language=" + facade.promptRuntime.language)
    print("program_class=" + facade.retaProgram.class_name)
