"""Generated traversal catalog for the native Grundstrukturen HTML renderer.

Source: ``python_reference/grundStrukHtml.py`` and its localized
``wahl15`` data. Regenerate with
``tools/generate_grundstrukturen_catalog.py``.
"""

from std.collections import List


@fieldwise_init
struct GrundstrukturRenderRecord(Copyable):
    var depth: Int
    var key: String
    var is_leaf: Bool
    var open_div: Bool
    var show_text: Bool


def german_basic_structures_label() -> String:
    return "Grundstrukturen"


def international_basic_structures_label() -> String:
    return "basic_structures"


def german_grundstruktur_records() -> List[GrundstrukturRenderRecord]:
    var records = List[GrundstrukturRenderRecord]()
    records.append(GrundstrukturRenderRecord(0, "Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "Geist_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "Model_of_Hierarchical_Complexity", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "Biologischer_Baum_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "Teilchen_anderes_Universum", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(1, "7mit6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Wohlbefinden_(7mit6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "gegen5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "gegen_5", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Bewusstheit_statt_Bewusstsein_(1)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "2", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Konkreta_und_Focus_(2)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "3", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Existenzialien_(3)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Reflexe_(3)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/3", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Bedingung_und_Auslöser_(1/3)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "4", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Achtung_(4)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Impulse_(5)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Bedeutung_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Bestrebungen(1/5)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "System", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Triebe_und_Bedürfnisse_(6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "innere_Werte_1/6_der_Reinigung_und_Klarheit", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "7", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Erlösung", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Anführer_Arten_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Gefühle_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "8", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Gewalt", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Bestrafung", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Modus_und_Sein_(8)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/8", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Prinzipien(1/8)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "9", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Lust_(9)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Größenordnung", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "10", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Wirklichkeiten_Wahrheit_Wahrnehmung_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "4", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "Zeit_(4)_als_Wirklichkeit", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "18", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(5, "relativer_Zeit-Betrag_(15_10_4_18_6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "11", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Verhalten_(11)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "12", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Ordnung_und_Filterung_12_und_1pro12", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Meta-Systeme_(12)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/12", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Karte_Filter_und_Unterscheidung_(1/12)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "13", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Paradigmen_sind_Absichten_(13)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_6_ist_Vorteilsmaximierung", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "7", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_7_ist_Selbstlosigkeit", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_10_ist_Wirklichkeit_erkennen", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "17", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_17_ist_zu_meinen", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "1/8", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_1/8", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "1/6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_1/6_ist_Reinigung_und_Klarheit", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "16", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_16_ist_zu_genügen", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "13", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Absicht_13_ist_Helfen", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "4", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Taetigkeiten", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/13", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Sollen_Frage_Vorgehensweise_(1/13)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "14", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Stimmungen_Kombinationen_(14)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Rechnen", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Teilchen_anderes_Universum", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Biologischer_Baum_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Model_of_Hierarchical_Complexity", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Geist_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/15", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Reflektion_und_Kategorien_(1/15)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "16", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Funktionen_Vorstellungen_(16)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "17", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Gedanken_sind_Positionen_(17)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "Themen_(6)", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "10mit4", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "Optimierung_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "18", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Verbundenheiten_(18)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "7", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Liebe_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Koalitionen_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "17", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Ansichten_Standpunkte_(18_17)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "Zahlenvergleich_(15_18_6)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "universeller_Komperativ_(18→15)", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "n-vs-1/n", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "Relation_zueinander_reziprok_Universellen_(18→n_vs._1/n)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "19", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Ziele_(19)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "Extremalien_(19)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/19", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Fundament_(1/19)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "20", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Klassen_(20)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "21", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Leidenschaften_(21)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "24", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Netzwerk", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "26", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Erwartungshaltungen_(26)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "28", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Lebensbereiche_Problemklassen_(28)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "30", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Energie_und_universelle_Eigenschaften_(30)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/30", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "analytische_Ontologie", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "31", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Garben_und_Verhalten_nachfühlen(31)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "32", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "mathematisches_Design_(32)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "36", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Attraktionen_(36)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "37", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Empathie_(37)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "39", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Maßnahmen_(39)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "51", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "Kontroverse_(51)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "90", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "abhängige_Verbundenheit_(90)", True, False, True))
    return records^


def international_grundstruktur_records() -> List[GrundstrukturRenderRecord]:
    var records = List[GrundstrukturRenderRecord]()
    records.append(GrundstrukturRenderRecord(0, "structural_paradigms_or_meta-paradigms_or_transcendental_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "mind_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "model_of_Hierarchical_Complexity", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "biological_tree_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "particles_other_universe", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "comprehend_emotionally_or_mentally_by_prime_cross_algorithm_(15)", True, True, True))
    records.append(GrundstrukturRenderRecord(0, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(1, "7with6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "well-being_(7with6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "against5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "against_5", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "awareness_instead_of_consciousness_(1)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "2", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "concretes_and_Focus_(2)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "3", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "existentials_(3)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "reflexes_(3)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/3", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "condition_and_trigger_(1/3)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "4", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "attention_(4)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "impulses_(5)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "meaning_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/5", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "aspirations(1/5)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "system", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "drives_and_needs_(6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/6", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "inner-values_1/6_of_cleaning_and_clarity", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "7", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "salvation", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "leadership_types_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "feelings_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "8", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "violence", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "punishment", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "mode_and_being_(8)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/8", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "principles(1/8)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "9", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "lust_(9)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "scale", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "10", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "realities_truth_perception_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "4", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "time_(4)_as_reality", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "18", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(5, "relative_time_amount_(15_10_4_18_6)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "11", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "behavior_(11)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "12", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "order_and_Filtering_12_and_1pro12", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "meta-systems_(12)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/12", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "map_filter_and_distinction_(1/12)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "13", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "paradigms_are_intentions_(13)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_6_is_advantage_maximization.", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "7", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_7_is_selflessness", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_10_is_recognition_of_reality", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "17", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_17_is_to_mean_opionions", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "1/8", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_1/8", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "1/6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_1/6_is_cleaning_and_clarity", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "16", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_16_is_to_be_enough", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "13", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "intention_13_is_helping", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "4", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "actions", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/13", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "shall_question_procedure_(1/13)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "14", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "moods_combinations_(14)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "calculate", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "comprehend_emotionally_or_mentally_by_prime_cross_algorithm_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "particles_other_universe", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "biological_tree_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "model_of_Hierarchical_Complexity", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "mind_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "structural_paradigms_or_meta-paradigms_or_transcendental_(15)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/15", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "reflection_and_Categories_(1/15)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "16", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "functions_Conceptions_(16)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "17", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "thoughts_are_positions_(17)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "topics_(6)", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "10with4", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "optimization_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "18", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "connections_(18)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "7", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "love_(7)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "10", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "coalitions_(10)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "17", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "views_Stances_(18_17)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "6", False, False, False))
    records.append(GrundstrukturRenderRecord(3, "comparision_of_numbers_(15_18_6)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "15", False, True, True))
    records.append(GrundstrukturRenderRecord(3, "universal_comperative_(18→15)", True, False, True))
    records.append(GrundstrukturRenderRecord(3, "n-vs-1/n", False, False, False))
    records.append(GrundstrukturRenderRecord(4, "relation_to_each_other_reciprocal_universal_(18→n_vs._1/n)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "19", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "goals_(19)", True, False, True))
    records.append(GrundstrukturRenderRecord(2, "extremalias_(19)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/19", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "foundation_(1/19)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "20", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "classes_(20)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "21", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "passions_(21)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "24", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "network", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "26", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "expectations_(26)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "28", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "areas_of_life_and_classes_of_problems(28)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "30", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "energy_and_universal_properties_(30)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "1/30", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "analytic_ontology", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "31", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "sheaf_and_behavior_empathy_(31)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "32", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "mathematical_design_(32)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "36", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "attractions_(36)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "37", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "empathy_(37)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "39", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "measures_(39)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "51", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "controversy_(51)", True, False, True))
    records.append(GrundstrukturRenderRecord(1, "90", False, True, True))
    records.append(GrundstrukturRenderRecord(2, "dependent_connectedness_(90)", True, False, True))
    return records^


