"""Generated native snapshot of reta i18n/schema data.

Regenerate with tools/generate_schema_catalog.py.
"""

from std.collections import List
from .schema import *


def bootstrap_reta_schema() -> RetaContextSchema:
    var language_aliases = List[NamedValue]()
    language_aliases.append(NamedValue("english", "en"))
    language_aliases.append(NamedValue("englisch", "en"))
    language_aliases.append(NamedValue("deutsch", "de"))
    language_aliases.append(NamedValue("german", "de"))
    language_aliases.append(NamedValue("vietnamesisch", "vn"))
    language_aliases.append(NamedValue("vietnamese", "vn"))
    language_aliases.append(NamedValue("tiếngviệt", "vn"))
    language_aliases.append(NamedValue("chinesisch", "cn"))
    language_aliases.append(NamedValue("chinese", "cn"))
    language_aliases.append(NamedValue("中國人", "cn"))
    language_aliases.append(NamedValue("koreanisch", "kr"))
    language_aliases.append(NamedValue("korean", "kr"))
    language_aliases.append(NamedValue("한국인", "kr"))
    var translation_domains = List[NamedValue]()
    translation_domains.append(NamedValue("english", "messages"))
    translation_domains.append(NamedValue("englisch", "messages"))
    translation_domains.append(NamedValue("deutsch", "messages"))
    translation_domains.append(NamedValue("german", "messages"))
    translation_domains.append(NamedValue("vietnamesisch", "vn"))
    translation_domains.append(NamedValue("vietnamese", "vn"))
    translation_domains.append(NamedValue("tiếngviệt", "vn"))
    translation_domains.append(NamedValue("chinesisch", "cn"))
    translation_domains.append(NamedValue("chinese", "cn"))
    translation_domains.append(NamedValue("中國人", "cn"))
    translation_domains.append(NamedValue("koreanisch", "kr"))
    translation_domains.append(NamedValue("korean", "kr"))
    translation_domains.append(NamedValue("한국인", "kr"))
    var parameters_main = List[AliasGroup]()
    parameters_main.append(AliasGroup("Wichtigstes_zum_verstehen", ["Wichtigstes_zum_verstehen", "wichtigsteverstehen"]))
    parameters_main.append(AliasGroup("Wichtigstes_zum_gedanklich_einordnen", ["Wichtigstes_zum_gedanklich_einordnen", "wichtigsteeinordnen"]))
    parameters_main.append(AliasGroup("Religionen", ["Religionen", "religionen", "religion"]))
    parameters_main.append(AliasGroup("Galaxie", ["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"]))
    parameters_main.append(AliasGroup("Größenordnung", ["Größenordnung", "groessenordnung", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße", "groesse", "stufe", "organisationen"]))
    parameters_main.append(AliasGroup("Universum", ["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"]))
    parameters_main.append(AliasGroup("Multiversum", ["Multiversum", "multiversum"]))
    parameters_main.append(AliasGroup("Wirtschaft", ["Wirtschaft", "wirtschaft"]))
    parameters_main.append(AliasGroup("Menschliches", ["Menschliches", "menschliches"]))
    parameters_main.append(AliasGroup("Pro_Contra", ["Pro_Contra", "procontra", "dagegendafuer"]))
    parameters_main.append(AliasGroup("Licht", ["Licht", "licht"]))
    parameters_main.append(AliasGroup("Bedeutung", ["Bedeutung", "bedeutung"]))
    parameters_main.append(AliasGroup("Symbole", ["Symbole", "symbole"]))
    parameters_main.append(AliasGroup("Multiplikationen", ["Multiplikationen"]))
    parameters_main.append(AliasGroup("Eigenschaften_n", ["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"]))
    parameters_main.append(AliasGroup("Eigenschaften_1/n", ["Eigenschaften_1/n", "konzept2", "konzepte2"]))
    parameters_main.append(AliasGroup("Inkrementieren", ["Inkrementieren", "inkrementieren"]))
    parameters_main.append(AliasGroup("Operationen", ["Operationen", "operationen"]))
    parameters_main.append(AliasGroup("Meta_vs_Konkret_(Universum)", ["Meta_vs_Konkret_(Universum)", "universummetakonkret"]))
    parameters_main.append(AliasGroup("Primzahlwirkung", ["Primzahlwirkung", "primzahlwirkung"]))
    parameters_main.append(AliasGroup("gebrochen-rational_Universum_n/m", ["gebrochen-rational_Universum_n/m", "gebrochenuniversum"]))
    parameters_main.append(AliasGroup("gebrochen-rational_Galaxie_n/m", ["gebrochen-rational_Galaxie_n/m", "gebrochengalaxie"]))
    parameters_main.append(AliasGroup("gebrochen-rational_Gefuehle_n/m", ["gebrochen-rational_Gefuehle_n/m", "gebrochenemotion"]))
    parameters_main.append(AliasGroup("gebrochen-rational_Strukturgroesse_n/m", ["gebrochen-rational_Strukturgroesse_n/m", "gebrochengroesse"]))
    parameters_main.append(AliasGroup("Multiplikationen", ["Multiplikationen", "multiplikationen"]))
    parameters_main.append(AliasGroup("Planet_(10_und_oder_12)", ["Planet_(10_und_oder_12)", "planet"]))
    parameters_main.append(AliasGroup("Strukturen_1_bis_9", ["Strukturen_1_bis_9", "strukturkleinerzehn"]))
    parameters_main.append(AliasGroup("Grundstrukturen", ["Grundstrukturen", "grundstrukturen"]))
    parameters_main.append(AliasGroup("Teilchen-Meta-Physik", ["Teilchen-Meta-Physik", "teilchen"]))
    parameters_main.append(AliasGroup("Kontinuum", ["Kontinuum", "kontinuum"]))
    parameters_main.append(AliasGroup("Herrschaft", ["Herrschaft", "macht"]))
    parameters_main.append(AliasGroup("MetaMetaPhysik_und_MetaChemie", ["MetaMetaPhysik_und_MetaChemie"]))
    parameters_main.append(AliasGroup("alles", ["alles"]))
    var row_parameters = List[NamedValue]()
    row_parameters.append(NamedValue("alles", "alles"))
    row_parameters.append(NamedValue("gestern", "gestern"))
    row_parameters.append(NamedValue("heute", "heute"))
    row_parameters.append(NamedValue("hoehemaximal", "hoehemaximal"))
    row_parameters.append(NamedValue("mond", "mond"))
    row_parameters.append(NamedValue("morgen", "morgen"))
    row_parameters.append(NamedValue("nachtraeglichneuabzaehlung", "nachtraeglichneuabzaehlung"))
    row_parameters.append(NamedValue("nachtraeglichneuabzaehlungvielfache", "nachtraeglichneuabzaehlungvielfache"))
    row_parameters.append(NamedValue("oberesmaximum", "oberesmaximum"))
    row_parameters.append(NamedValue("planet", "planet"))
    row_parameters.append(NamedValue("potenzenvonzahlen", "potenzenvonzahlen"))
    row_parameters.append(NamedValue("primzahlvielfache", "primzahlvielfache"))
    row_parameters.append(NamedValue("schwarzesonne", "schwarzesonne"))
    row_parameters.append(NamedValue("sonne", "sonne"))
    row_parameters.append(NamedValue("typ", "typ"))
    row_parameters.append(NamedValue("vielfachevonzahlen", "vielfachevonzahlen"))
    row_parameters.append(NamedValue("vorhervonausschnitt", "vorhervonausschnitt"))
    row_parameters.append(NamedValue("vorhervonausschnittteiler", "vorhervonausschnittteiler"))
    row_parameters.append(NamedValue("zaehlung", "zaehlung"))
    row_parameters.append(NamedValue("zeit", "zeit"))
    row_parameters.append(NamedValue("primzahlen", "primzahlen"))
    row_parameters.append(NamedValue("aussenerste", "aussenerste"))
    row_parameters.append(NamedValue("innenerste", "innenerste"))
    row_parameters.append(NamedValue("aussenalle", "aussenalle"))
    row_parameters.append(NamedValue("innenalle", "innenalle"))
    row_parameters.append(NamedValue("invertieren", "invertieren"))
    row_parameters.append(NamedValue("SonneMitMondanteil", "SonneMitMondanteil"))
    var output_parameters = List[NamedValue]()
    output_parameters.append(NamedValue("nocolor", "nocolor"))
    output_parameters.append(NamedValue("justtext", "justtext"))
    output_parameters.append(NamedValue("art", "art"))
    output_parameters.append(NamedValue("onetable", "onetable"))
    output_parameters.append(NamedValue("spaltenreihenfolgeundnurdiese", "spaltenreihenfolgeundnurdiese"))
    output_parameters.append(NamedValue("endlessscreen", "endlessscreen"))
    output_parameters.append(NamedValue("endless", "endless"))
    output_parameters.append(NamedValue("dontwrap", "dontwrap"))
    output_parameters.append(NamedValue("breite", "breite"))
    output_parameters.append(NamedValue("breiten", "breiten"))
    output_parameters.append(NamedValue("keineleereninhalte", "keineleereninhalte"))
    output_parameters.append(NamedValue("keinenummerierung", "keinenummerierung"))
    output_parameters.append(NamedValue("keineueberschriften", "keineueberschriften"))
    var output_modes = List[NamedValue]()
    output_modes.append(NamedValue("bbcode", "bbcode"))
    output_modes.append(NamedValue("html", "html"))
    output_modes.append(NamedValue("csv", "csv"))
    output_modes.append(NamedValue("shell", "shell"))
    output_modes.append(NamedValue("markdown", "markdown"))
    output_modes.append(NamedValue("emacs", "emacs"))
    output_modes.append(NamedValue("nichts", "nichts"))
    var combination_parameters = List[NamedValue]()
    combination_parameters.append(NamedValue("galaxie", "galaxie"))
    combination_parameters.append(NamedValue("universum", "universum"))
    var scopes = List[NamedValue]()
    scopes.append(NamedValue("zeilen", "zeilen"))
    scopes.append(NamedValue("spalten", "spalten"))
    scopes.append(NamedValue("kombination", "kombination"))
    scopes.append(NamedValue("ausgabe", "ausgabe"))
    scopes.append(NamedValue("h", "h"))
    scopes.append(NamedValue("help", "help"))
    scopes.append(NamedValue("debug", "debug"))
    scopes.append(NamedValue("nichts", "nichts"))
    var parameter_entries = List[ParameterEntry]()
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_verstehen", "wichtigsteverstehen"], ["Wichtigste", "wichtigste"], [4, 5, 8, 10]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Mensch-zu-Tier", "menschtier", "tiermensch"], [314]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Verbrechen_und_Bestrafung", "kriminell", "bestrafen"], [539, 540]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Galaxienclusterherrschaft", "cluster", "interglaktisch"], [538]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Herrschaftsformen", "formen", "Strukturgroesse", "groesse", "Größe"], [603, 617]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Orbit-Herrschafts", "orbit", "Massenmedien", "Satelliten"], [548]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Herrschafts_Datenstruktur", "struktur"], [541, 544]))
    parameter_entries.append(ParameterEntry(["MetaMetaPhysik_und_MetaChemie"], ["Meta_Meta_Physik_Einteilungen"], [670, 671, 672, 673, 674, 675]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Sternen_System", "sonne"], [545]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Galaxieherrschaft", "Galaxie", "galaxie"], [537, 604]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["abstrakte_Herrschaft", "abstrakt"], [564, 573]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Winkel", "winkel"], [726]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Logik", "logik"], [725]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Logik", "logik"], [725]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Kreislaufwirtschaft", "kreislauf", "Kreislauf"], [610]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Planetenherrschaft", "herrschaft", "Planetenkorrekturherrschaft"], [536, 542, 562, 588, 664]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Spezies", "Speziesherrschaftsformen"], [668, 669]))
    parameter_entries.append(ParameterEntry(["Herrschaft", "macht"], ["Planetenherrschaft", "planet", "Planetenkorrektur"], [536, 542, 562, 588, 664]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Superkräfte", "Superkraefte"], [444, 494, 496, 503]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Superkräfte", "Superkraefte"], [444, 494, 496]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Objekte", "objekt"], [546]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Evolution_vs_Design_intelligent"], [519]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gott_und_Prophet", "goetter"], [534, 550, 552, 553, 557]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Sinne"], [533]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Superkräfte", "Superkraefte"], [444, 494, 496]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Formationen"], [461]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Ansichten_Standpunkte_(18_17)", "ansichten"], [240, 346]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["(politische)_Richtungen_(7)", "richtungen", "politische"], [235]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Wirklichkeiten_(10)", "wirklichkeit", "wirklichkeiten"], [233, 265, 268, 322, 420]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Meta-Systeme_(12)", "metasysteme", "metasystem", "meta-systeme", "meta-system"], [79, 80, 232, 288, 334, 410, 411, 483, 497, 498, 499]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Intelligenz", "intelligenz"], [214]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Gleichheit_Freiheit_Ordnung", "gleichheit", "freiheit", "gleichheit"], [79, 80, 132, 324, 328, 331, 335, 497, 498, 499]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Komplexität", "komplexität", "komplexitaet"], [213]))
    parameter_entries.append(ParameterEntry(["Planet_(10_und_oder_12)", "planet"], ["Mechanismen", "mechanismen", "mechanismus"], [107]))
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_verstehen", "wichtigsteverstehen"], ["Zweitwichtigste", "zweitwichtigste"], [19, 65, 183]))
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_verstehen", "wichtigsteverstehen"], ["Drittwichtigste", "drittwichtigste"], [64]))
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_verstehen", "wichtigsteverstehen"], ["Motive_Sternpolygone", "viertwichtigste"], []))
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_gedanklich_einordnen", "wichtigsteeinordnen"], ["Wichtigste", "wichtigstes"], [0, 1, 2, 36, 37, 207]))
    parameter_entries.append(ParameterEntry(["Wichtigstes_zum_gedanklich_einordnen", "wichtigsteeinordnen"], ["Zweitwichtigste", "zweitwichtigste"], [30]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["Halbierung", "halbierung", "halbierungen"], [86]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Religions-Gründer-Typ", "religionsgründertyp", "prophet", "archon", "religionsgruendertyp"], [72, 503]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Satan_Teufel"], [495]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Satan_Teufel"], [495]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Hinduismus", "hinduismus"], [217]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Sternpolygon", "sternpolygon"], [0, 6, 36]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["der_Tierkreiszeichen", "dertierkreiszeichen", "babylon"], [0, 36, 207, 477, 478]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Sternpolygon_vs_gleichförmiges", "vergleich", "sternpolygonvsgleichfoermiges", "vergleichnvs1divn"], [87]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Messias", "messias", "heptagramm", "hund", "messiase", "messiasse"], [7, 503]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["gleichförmiges_Polygon", "gleichförmigespolygon", "gleichfoermigespolygon", "nichtsternpolygon", "polygon"], [16, 37]))
    parameter_entries.append(ParameterEntry(["Religionen", "religionen", "religion"], ["Vertreter_höherer_Konzepte", "vertreterhoehererkonzepte", "galaxien", "galaxie", "schwarzesonne", "schwarzesonnen", "universum", "universen", "kreis", "kreise", "kugel", "kugeln"], [23]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Lebewesen_Galaxie_am_Besten"], [470, 471, 473]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Offenbarung_des_Johannes", "offenbarung", "offenbarungdesjohannes", "johannes", "bibel", "offenbarungjohannes"], [90]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["Teilchen-Meta-Physik", "addition", "identitaet", "Identität"], [219, 223, 307, 308, 333, 387, 388, 406]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Hochzüchten", "hochzüchten", "hochzuechten"], [318, 319]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Farben", "farbe", "Farben_Sind_Signale_Signale_sind_Dimension_Dreizehn"], [624, 659]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Maschinen", "Computer", "computer", "maschinen"], [89, 592, 593, 685, 686, 687]))
    parameter_entries.append(ParameterEntry(["MetaMetaPhysik_und_MetaChemie"], ["Kybernetik_und_Meta_Chemie", "kybernetik", "metachemie"], [606]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Kybernetik_und_Meta_Chemie", "kybernetik", "metachemie"], [606]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Teilchen_anderes_Universum"], [512]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Teilchen_anderes_Universum"], [512]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Entwicklungs_Stadium_Spezies", "Spezies_Entwicklung"], [661]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Teilchen_anderes_Universum"], [512]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Zusammenhang_Gehirn_Kosmos_Universum"], [489]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Zahlenarten", "zahlen", "nummern"], [462, 563, 704, 717, 724, 728]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Bestrafung", "bestrafen"], [636]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Diplomatie", "diplomatie", "lateral"], [523, 594]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Bestrafung"], [463]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Bestrafung"], [463]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["weniger_am_Menschen"], [464]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Erlösung", "Erloesung"], [465]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Erlösung", "Erloesung"], [465]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gewalt"], [466]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Gewalt"], [466, 479]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Farben"], [444]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["künstliches_Leben_(15)", "künstlichesleben", "grosseki"], [409]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Software-Lizenzen_akademische_Grade", "softwarelizenz", "akademischeGrade"], [422]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Strategie_Taktik_(15m8)", "strategie", "taktik"], [385]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Universelles_Verhältnis_gleicher_Zahlen", "verhaeltnisgleicherzahl"], [383]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["universelles_Recht", "recht", "jura"], [34, 65, 382]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["sowas_wie_Kombinieren_Verknüpfen", "kombinierenetc"], [320]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Hochzüchten", "hochzüchten", "hochzuechten"], [318, 319]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Teilchen-Meta-Physik"], [219, 308]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["das_Universelle_(15)"], [219, 308]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["Wirklichkeiten_(10)", "wirklichkeit", "wirklichkeiten"], [420]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["das_Galaktische_(14)"], [406]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["das_Multiverselle_(16)"], [388, 418]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["die_Tugendsortierung_(13_mit_14)"], [411]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["die_Galaxie_Unterbereiche_(13)"], [223, 307, 412]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["das_Gute_die_Richtung_(7)"], [333]))
    parameter_entries.append(ParameterEntry(["Teilchen-Meta-Physik", "teilchen"], ["Raum_und_Dimensionen_(8)"], [387]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["keine_Nur-Paradigma-Religionen", "metaparadigmareligion"], [190, 191, 196]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Kugeln_Kreise", "kugelnkreise", "kugeln", "kreise"], [77, 145]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Raumzeit_Anordnung_mathematisch_universell"], [472]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Multiversalien_(16)", "multiversalien"], [389]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Meta-Physik-Teilchen_(1)", "teilchen"], [388]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Kugeln_Kreise", "kugelnkreise", "kugeln", "kreise"], [77, 145]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["chinesisches_Horoskop", "chinesischeshoroskop", "china"], [91]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["babylonische_Tierkreiszeichen", "tierkreiszeichen", "babylon"], [1, 2]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Thomasevangelium", "thomasevangelium", "thomas"], [0, 3, 303]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Netzwerk", "netzwerk"], [417, 436]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Kontroverse_(51)", "kontroverse"], [421]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["mathematisches_Design_(32)", "mathematischesdesign"], [419]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["analytische_Ontologie", "analytischeontologie", "ontologie"], [84]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["analytische_Ontologie", "analytischeontologie", "ontologie"], [84]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Transzendentalien_innen_außen", "innenaussenstrukur", "strukturalieninnenaußen", "strukturalieninnenaussen", "innenaußenstrukur", "transzendentalieninnenaußen", "transzendentalieninnenaussen"], [149]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Modallogik", "modallogik"], [148]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["5", "fünf", "fünfer", "fünferstruktur", "fuenf", "fuenfer", "fuenferstruktur"], [96]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["9", "neun", "neuner", "neunerstruktur"], [94]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["3", "drei", "dreier", "dreierstruktur"], [92, 93, 315, 316]))
    parameter_entries.append(ParameterEntry(["Größenordnung", "groessenordnung", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße", "groesse", "stufe", "organisationen"], ["Licht", "licht"], [20, 27, 313]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Strukturgrösse", "Größenordnung", "größe", "groesse", "gross", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße"], [4, 21, 54, 197, 425, 745]))
    parameter_entries.append(ParameterEntry(["Größenordnung", "groessenordnung", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße", "groesse", "stufe", "organisationen"], ["Strukturgrösse", "Größenordnung", "größe", "groesse", "gross", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße"], [4, 21, 54, 197, 425, 745]))
    parameter_entries.append(ParameterEntry(["Größenordnung", "groessenordnung", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße", "groesse", "stufe", "organisationen"], ["Organisationen", "organisationen", "organisation"], [30, 82, 425, 745]))
    parameter_entries.append(ParameterEntry(["Größenordnung", "groessenordnung", "strukturgroesse", "strukturgroeße", "strukturgrösse", "strukturgröße", "groesse", "stufe", "organisationen"], ["politische_Systeme", "politischesysteme", "politik"], [83]))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["meta"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["konkret"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Theorie", "theorie"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Praxis", "praxis"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Management", "management", "stau"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["verändernd", "veraendernd", "fluss"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["ganzheitlich", "mathematisch_diskret", "diskret"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["darüber_hinausgehend", "hinausgehend", "kontinuierlich"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Universum_Strukturalien_Transzendentalien", "universum", "strukturalie", "strukturalien", "transzendentalien", "transzendentalie"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Richtung_als_Richtung", "richtungrichtung"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Galaxieabsicht", "absichtgalaxie", "absicht", "motive", "motiv", "absichten", "galaxie"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Absicht_Reziproke_Galaxie", "absichtgalaxiereziproke", "absichtreziproke", "motivereziproke", "motivreziproke", "absichtenreziproke", "galaxiereziproke"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Universum_Reziproke", "universumreziproke", "strukturaliereziproke", "strukturalienreziproke", "transzendentalienreziproke", "transzendentaliereziproke"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["Dagegen-Gegentranszendentalie", "dagegengegentranszendentalie", "dagegengegentranszendentalien", "dagegengegenstrukturalien", "dagegengegenstrukturalie"], []))
    parameter_entries.append(ParameterEntry(["Primzahlwirkung", "primzahlwirkung"], ["neutrale_Gegentranszendentalie", "neutralegegentranszendentalie", "neutralegegentranszendentalien", "neutralegegenstrukturalien", "neutralegegenstrukturalie"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Unternehmung_Geschäft", "unternehmen", "unternehmung", "geschaeft", "geschäft"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["wertvoll", "wert"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Beherrschen", "regieren", "beherrschen"], []))
    parameter_entries.append(ParameterEntry(["Meta_vs_Konkret_(Universum)", "universummetakonkret"], ["Richtung", "richtung", "gut"], []))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["analytische_Ontologie", "analytischeontologie", "ontologie"], [84]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Gegentranszendentalien", "gegentranszendentalien", "gegentranszendentalie", "gegenstrukturalien", "gegenalien", "gegenuniversalien"], [138, 202]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Systemsachen", "systemsachen"], [150]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Transzendentalien", "transzendentalien", "transzendentalie", "strukturalien", "alien", "universalien"], [5, 54, 55, 198, 390]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Reziproke_von_Transzendentalien", "transzendentalienreziproke", "transzendentaliereziproke", "strukturalienreziproke", "alienreziproke", "universalienreziproke"], [131, 201]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Netzwerk", "netzwerk"], [25, 55, 386, 390]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["warum_Transzendentalie_=_Strukturgroesse_=_Charakter", "warumtranszendentaliezustrukturgroesseundcharakter"], [4, 5, 54, 165]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Kategorie", "kategorie"], [204, 205, 281]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Raum-Missionen", "weltall"], [218]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Programmier-Paradigmen", "programmierparadigmen"], [351]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["ZergAliens_MenschenHumanoid_ProtosPraedatoren"], [521]))
    parameter_entries.append(ParameterEntry(["Galaxie", "galaxie", "alteschriften", "kreis", "galaxien", "kreise"], ["Raum-Missionen", "weltall"], [218]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Geist__(15)", "geist"], [242, 426]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["warum_Transzendentalie_=_Komplexität_von_Michael_Commons", "warumtranszendentaliegleichkomplexitaet"], [5, 65, 166]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Model_of_Hierarchical_Complexity", "modelofhierarchicalcomplexity", "komplex", "komplexität", "komplexitaet", "complexity", "model", "abstraktion"], [65, 75, 203, 483]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Model_of_Hierarchical_Complexity", "modelofhierarchicalcomplexity", "komplex", "komplexität", "komplexitaet", "complexity", "model", "abstraktion"], [65, 75, 203]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Model_of_Hierarchical_Complexity", "modelofhierarchicalcomplexity", "komplex", "komplexität", "komplexitaet", "complexity", "model", "abstraktion"], [65, 75, 203]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["2", "zwei", "gerade", "ungerade", "alternierung", "alternierend", "zweierstruktur"], [78, 79, 80, 331, 497, 498, 499]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["Multiplikation", "multiplikation"], [158]))
    parameter_entries.append(ParameterEntry(["Operationen", "operationen"], ["4", "vier", "viererstruktur", "viererabfolgen"], [76, 77, 81, 104, 145]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Weltordnung", "Zeitalter"], [522]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Himmel_Hoelle_Kettenmolekuele"], [526]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Spiele-Genre"], [525]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Land_Laender-Dach-Organisation"], [524]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Ränge", "raenge"], [520, 535]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gesellschaftsschicht", "klasse", "klassen"], [241, 551, 555, 697]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Moral", "moral", "warummoral"], [215, 216]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Fachgebiete", "fachgebiete", "fachbereiche", "themen"], [183]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["Fachgebiete", "fachgebiete", "fachbereiche", "themen"], [183]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["Pflanzen", "pflanzen"], [113]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["Maschinen", "maschinen", "maschine", "gerät", "geräte", "geraete", "geraet"], [89, 592, 593, 685, 686, 687]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["Organisationsform", "organisationsform", "organisationsart", "firma", "verein"], [99]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["System", "system"], [69, 70, 440, 455, 476, 513]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["System", "system"], [69, 70, 440, 455, 476, 513]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["Erklärung", "erklärung", "erklaerung"], [71]))
    parameter_entries.append(ParameterEntry(["Wirtschaft", "wirtschaft"], ["BWL", "bwl"], [109]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Sinn_des_Lebens", "sinndeslebens", "lebenssinn", "sinn", "sinnsuche"], [88, 189]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Intelligenzprobleme", "intelligenzprobleme", "intelligenzmaengel", "intelligenzmängel"], [147]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Denkweise_von_Lebewesen", "lebewesendenkweise", "denkweise"], [146]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gegentranszendentalien", "gegentranszendentalien", "gegenstrukturalien"], [138, 139, 202]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gleichheit_Freiheit", "gleichheitfreiheit", "ungleichheit", "dominieren", "gleichheit", "freiheit"], [132, 328, 331, 335]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gefühle", "emotionen", "gefuehle", "emotion", "gefühl", "gefuehl"], [105, 230, 243, 283, 284, 285, 286, 305]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Egoismus", "egoismus", "altruismus", "selbstlosigkeit"], [136]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Wirkung", "wirkung"], [135]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["INCELs", "incel", "incels"], [68]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["irrationale_Zahlen_durch_Wurzelbildung", "irrationalezahlendurchwurzelbildung", "ausgangslage"], [73]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["dominierendes_Geschlecht", "dominierendesgeschlecht", "maennlich", "männlich", "weiblich"], [51]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Liebe", "liebe", "ethik"], [8, 9, 28, 208, 330, 580]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Glaube_Erkenntnis", "glauben", "erkenntnis", "glaube"], [59, 621]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Angreifbarkeit", "angreifbarkeit", "angreifbar"], [57, 58]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)", "Transzendentalien", "transzendentalien", "transzendentalie", "strukturalien", "alien", "universalien", "meta-paradigmen"], [5, 131, 229]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)", "Transzendentalien", "transzendentalien", "transzendentalie", "strukturalien", "alien", "universalien", "meta-paradigmen"], [5, 131, 229]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Bedingung_und_Auslöser_(1/3)", "bedingung", "bedingungen", "auslöser", "ausloeser"], [338]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Lebensbereiche_Problemklassen_(28)", "lebensbereiche", "lebensfelder", "problemklassen"], [405, 415, 416]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Maßnahmen_(39)", "massnahmen"], [384]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Relation_zueinander_reziprok_Universellen_(18→n_vs._1/n)", "relativreziprokuniversell"], [350]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["universeller_Komperativ_(18→15)", "universellerkomperativ"], [349]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Existenzialien_(3)", "existenzialien"], [348]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Extremalien_(19)", "extremalien"], [347, 352]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Erwartungshaltungen_(26)", "erwartungen", "erwartungshaltungen"], [344]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Leidenschaften_(21)", "leidenschaft", "leidenschaften"], [343]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["relativer_Zeit-Betrag_(15_10_4_18_6)", "relativerzeitbetrag"], [339]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Zahlenvergleich_(15_18_6)", "zahlenvergleich"], [340]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Bestrebungen(1/5)", "bestrebung", "bestrebungen"], [332, 414]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Prinzipien(1/8)", "prinzipien"], [329, 378]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Attraktionen_(36)", "attraktionen"], [311]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Optimierung_(10)", "optimierung"], [310]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Themen_(6)", "themen", "thema"], [309]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Bedeutung_(10)", "bedeutung"], [306]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Reziprokes", "reziproke", "reziprokes"], [42, 131, 204, 205, 231, 257, 273, 281, 284, 285, 326, 327, 328, 329, 330, 331, 332, 334, 335, 338, 416]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Achtung_(4)", "achtung", "achten"], [270, 393]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Zeit_(4)_als_Wirklichkeit", "zeit"], [266, 267]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_16_ist_zu_genügen", "absicht16"], [312]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_17_ist_zu_meinen", "absicht17"], [263]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_6_ist_Vorteilsmaximierung", "absicht6"], [262]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_7_ist_Selbstlosigkeit", "absicht7"], [261]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Bewusstheit_statt_Bewusstsein_(1)", "bewusstheit"], [282]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Verhalten_(11)", "verhalten"], [301, 302, 413]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Energie_und_universelle_Eigenschaften_(30)", "energie", "universelleeigenschaften", "lebensenergie"], [287, 293]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Garben_und_Verhalten_nachfühlen(31)", "garben", "verhaltenfuehlen", "verhaltenfühlen"], [295]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)", "nachvollziehen"], [242, 297]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Empathie_(37)", "empathie", "mitgefuehl"], [294]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_1/6_ist_Reinigung_und_Klarheit", "absicht1/6", "absicht1pro6"], [298]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["innere_Werte_1/6_der_Reinigung_und_Klarheit", "innerewerte"], [398, 399, 400, 401]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_10_ist_Wirklichkeit_erkennen", "absicht10"], [260]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Wohlbefinden_(7mit6)", "wohlbefinden"], [427, 428]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Geist_(15)", "geist", "bewusstsein"], [229, 231, 242, 273, 297, 304, 426]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Geist_(15)", "geist", "bewusstsein"], [229, 231, 242, 273, 297, 304, 426]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Reflexe_(3)", "reflex", "reflexe"], [256]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Lust_(9)", "lust", "einheiten"], [255, 391]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Paradigmen_sind_Absichten_(13)", "paradigmen", "absichten"], [10, 42, 410, 411, 493, 494]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Wirklichkeiten_Wahrheit_Wahrnehmung_(10)", "wirklichkeit", "wirklichkeiten", "wahrheit", "wahrnehmung"], [233, 265, 268, 322, 342, 480]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Rechnen", "rechnen"], [404]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Stimmungen_Kombinationen_(14)", "stimmung", "stimmungen", "kombination", "kombinationen"], [33, 290, 296, 325, 326, 327, 402, 403, 406, 407, 408, 430, 492]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Struktur-Wissenschaften_(10)"], [438]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Muster-Wissenschaften_(20)"], [439, 484]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Anführer_Arten_(7)"], [429, 455, 481, 482, 490, 497, 498, 499, 502, 509]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Klassen_(20)", "klasse", "klassen"], [241, 289, 394, 395, 485, 516, 697]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Ordnung_und_Filterung_12_und_1pro12", "ordnen", "ordnenundfiltern", "filtern"], [132, 328, 331, 335]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Meta-Systeme_(12)", "metasysteme", "metasystem", "meta-systeme", "meta-system", "menge", "mengen"], [79, 80, 232, 288, 334, 410, 411, 483, 497, 498, 499]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_1/8", "absicht1pro8", "absicht1/8"], [272, 379]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Ziele_(19)", "ziele", "maxima", "höhenvorstellungen"], [271]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Konkreta_und_Focus_(2)", "konkreta", "focus", "fokus"], [250, 253, 269]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Gefühle_(7)", "gefuehle", "emotionen", "emotion", "gefühle"], [29, 243, 283, 284, 285, 286, 305]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["abhängige_Verbundenheit_(90)", "abhaengigkeit", "abhängigkeit"], [357]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Karte_Filter_und_Unterscheidung_(1/12)", "karte", "filter", "unterscheidung"], [377]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Fundament_(1/19)", "fundament"], [356]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Gedanken_sind_Positionen_(17)", "positionen", "gedanken"], [249, 317, 323]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Funktionen_Vorstellungen_(16)", "vorstellungen", "vorstellung", "funktionen"], [264, 345, 388, 418]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Sollen_Frage_Vorgehensweise_(1/13)", "sollen", "frage", "vorgehensweise"], [353, 354]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Ansichten_Standpunkte_(18_17)", "ansichten"], [240, 346]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Psychopath_Soziopath", "sadist", "psychopath", "soziopath"], [581, 602]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Verbundenheiten_(18)", "verbundenheiten"], [252, 299, 300, 336, 580]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Verbundenheiten_(18)", "verbundenheiten"], [252, 299, 300, 336, 580]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Absicht_13_ist_Helfen", "absicht13", "helfen"], [370]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Liebe_(7)", "liebe"], [8, 9, 28, 208, 221, 330, 580]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Koalitionen_(10)", "koalitionen"], [321]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["gegen_5"], [24]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Impulse_(5)", "impulse"], [251, 253, 257, 341]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Triebe_und_Bedürfnisse_(6)", "trieb", "triebe", "bedürfnis", "bedürfnisse", "werte"], [254, 392, 396, 397, 423]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Taetigkeiten", "tätigkeiten", "taetigkeiten"], [424]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Reflektion_und_Kategorien_(1/15)", "reflektion", "kategorien"], [204, 205, 281]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Modus_und_Sein_(8)", "zustaende", "zustände", "modus", "modi", "sein"], [234, 337, 385, 387, 491]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Motive", "motive", "motivation", "motiv", "absicht", "absichten"], [10, 18, 42, 149, 167, 168, 229, 230, 561, 607]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Gedanken_sind_Positionen_(17)", "positionen", "gedanken"], [249, 276]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Bewusstsein_und_Wahrnehmung", "bewusstsein", "wahrnehmung"], [229, 231, 265, 281, 304, 342]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Errungenschaften", "errungenschaften", "ziele", "erhalten"], [11, 251, 257]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["evolutionär_erwerben_und_Intelligenz_Kreativität", "evolutionärerwerbenundintelligenz", "intelligenz", "erwerben", "erlernen", "lernen", "evolutionaer", "evolutionär", "kreativität", "kreativitaet", "kreativ"], [12, 13, 27, 32, 47]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["brauchen", "benoetigen", "benötigen", "notwendig"], [13, 14]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Krankheit", "krankheit", "krankheiten", "pathologisch", "pathologie", "psychiatrisch"], [24]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["alpha_beta", "alphabeta", "alpha", "beta", "omega", "sigma"], [46]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Anführer_und_Chef", "anfuehrer_und_boss"], [29, 170, 429, 455, 490, 502, 509, 708]))
    parameter_entries.append(ParameterEntry(["Grundstrukturen", "grundstrukturen"], ["Biologischer_Baum_(15)"], [500]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Biologischer_Baum_(16_->_5)"], [500]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Spezies_Typofikation", "spezies"], [582]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Biologischer_Baum_(15)"], [500]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Biologischer_Baum_(15)"], [500]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Manipulation", "manipulation"], [153]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Berufe", "berufe", "beruf"], [30]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Lösungen", "lösungen", "loesungen", "loesung", "lösungen"], [31]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Musik", "musik"], [33, 523]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["ergibt_Sinn", "ergibtsinn", "machtsinn", "sinn"], [140]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Veränderung", "veraenderung", "veraendern", "veränderung", "verändern"], [142]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["bändigen_kontrollieren", "baendigenkontrollieren", "kontrollieren", "baendigen", "bändigen"], [143]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["vereinen", "einheit"], [144]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Vorteile", "vorteile", "veraenderungnutzen"], [141]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Gegenspieler", "gegenspieler", "antagonist"], [137]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nervig"], [120]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["pro_nutzen", "pronutzen"], [117]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Gegenposition", "gegenposition"], [116]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Hilfe_erhalten", "hilfeerhalten"], [114]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Helfen", "helfen", "hilfe"], [115]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Pro", "pro", "dafür", "dafuer"], [17, 48]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nicht_miteinander_auskommen", "nichtauskommen"], [123]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nicht_dagegen", "nichtdagegen"], [124]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["kein_Gegenteil", "keingegenteil"], [125]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nicht_dafür", "nichtdafuer"], [126]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Hilfe_nicht_gebrauchen", "hilfenichtgebrauchen"], [127]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nicht_helfen_können", "nichthelfenkoennen"], [128]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["nicht_abgeneigt", "nichtabgeneigt"], [129]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["unmotivierbar"], [130]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["contra", "dagegen"], [15, 26]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Gegenteil", "gegenteil"], [100, 101, 222]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Harmonie", "harmonie"], [102, 103]))
    parameter_entries.append(ParameterEntry(["Licht", "licht"], [], [20, 27, 313]))
    parameter_entries.append(ParameterEntry(["Pro_Contra", "procontra", "dagegendafuer"], ["Primzahlkreuz_pro_contra", "primzahlkreuz"], []))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Primzahlkreuz_pro_contra", "primzahlkreuz"], []))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["in_ReTa", "inreta"], [209, 210, 474, 475]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Vorzeichen", "vorzeichen"], [118, 119]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Primzahlen", "primzahlen", "vielfache", "vielfacher"], [19]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Anwendung_der_Sonnen_und_Monde", "anwendungdersonnenundmonde", "anwendungdersonnen", "anwendungenfuermonde"], [22]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Zählungen", "zählungen", "zaehlung", "zaehlungen", "zählung"], [25, 45, 169, 188, 386, 390]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Jura", "jura", "gesetzeslehre", "recht"], [34]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Vollkommenheit_des_Geistes", "vollkommenheit", "geist"], [35]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Gestirn", "gestirn", "mond", "sonne", "planet"], [64, 154]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Konjunktiv_Wurzelbildung", "konjunktiv", "wurzel"], [106]))
    parameter_entries.append(ParameterEntry(["Bedeutung", "bedeutung"], ["Mechanismen_der_Züchtung", "mechanismen", "wesen", "zuechtung", "züchtung", "züchten", "zuechten"], [107, 108, 109]))
    parameter_entries.append(ParameterEntry(["gebrochen-rational_Galaxie_n/m", "gebrochengalaxie"], ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"], []))
    parameter_entries.append(ParameterEntry(["gebrochen-rational_Universum_n/m", "gebrochenuniversum"], ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"], []))
    parameter_entries.append(ParameterEntry(["gebrochen-rational_Gefuehle_n/m", "gebrochenemotion"], ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"], []))
    parameter_entries.append(ParameterEntry(["gebrochen-rational_Strukturgroesse_n/m", "gebrochengroesse"], ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"], []))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Religionen"], [36, 37]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Drei"], [452, 460]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Vier"], [453]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Fünf", "Fuenf"], [454]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Sechs"], [457]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Sieben"], [457]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Acht"], [458]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Neun"], [459]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Zehn"], [456]))
    parameter_entries.append(ParameterEntry(["Symbole", "symbole"], ["Zwölf", "Zwoelf"], [456]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Weisheit_etc", "weisheit", "metaweisheit", "meta-weisheit", "idiot", "weise", "optimal", "optimum"], [112]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Dein_Recht_bekommen", "rechte", "recht", "selbstgerecht"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["unterlegen_überlegen", "unterlegen", "ueberlegen"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Ehrlichkeit_und_Streit", "streit", "ehrlichkeit"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Würdig", "wuerdig", "würdig"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Regel_vs_Ausnahme", "regel", "ausnahme"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Filterart_Widrigkeit", "filterart", "widrigkeit"], [331, 335]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Werte", "werte"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Gutartigkeits-Egoismus", "position", "gutesreziprok"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Reflektieren_Erkenntnis-Erkennen", "reflektieren", "erkenntnis"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Vertrauen_wollen", "vertrauenwollen"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["einklinken_vertrauen_anprangern", "einklinken", "vertrauenerhalten", "anprangern"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Ausrichten_Einrichten", "einrichten", "ausrichten"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_1/n", "konzept2", "konzepte2"], ["Toleranz_Respekt_Akzeptanz_Willkommen", "toleranz", "respekt", "akzeptanz", "willkommen"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["familiebrauchen"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["ego", "bescheiden"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Selbstsucht_Ichsucht_etc", "selbstsucht", "ichsucht"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Forschen_Erfinden_Einklinken", "wissenschaft", "forschen", "einklinken", "erfinden"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Kooperation_vs_Arsch", "arschloch", "kooperation", "arsch"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Liebe_usw", "liebe", "zuneigung"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Selbstlosigkeit_Ichlosigkeit_etc", "selbstlos", "ichlos"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["variationsreich_eintönig", "eintönig", "eintoenig", "variationsreich"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Zuneigung_Abneigung", "abgeneigt", "zugewandt", "reserviert", "zugeneigt"], []))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["ehrlich_vs_höflich", "ehrlich", "höflich", "hoeflich"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["ehrlich_vs_höflich", "ehrlich", "höflich", "hoeflich"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Tragweite", "tragweite"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["wertvoll", "wertlos"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Götter_Propheten_Familien_Freunde", "familiaer", "goettlich", "freunde", "propheten"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["sanft_vs_hart", "sanft", "hart"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["vereinen_vs_verbinden", "vereinenverbinden", "vereinen", "verbinden", "einheit", "verbindung"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["ähnlich", "aehnlich"], [220]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["gut_böse_lieb_schlecht", "gut", "böse", "boese", "lieb", "schlecht"], [52, 53]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Sinn_und_Zweck_des_Lebens", "sinn", "zweck", "bedeutung"], [88, 189]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Zeit_vs_Raum", "zeit", "raum", "zeitlich", "räumlich"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["egalitär_vs_autoritär", "egalitaerautoritaer", "egalitaer", "autoritaer", "egalitär", "autoritär"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Meinungen_und_Ruf", "meinungen", "anderemenschen", "ruf"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Meinungsintelligenz", "meinungsintelligenz", "ursprungsintelligenz"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Sittlichkeit", "sittlichkeit", "annaehrerung"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Führung", "führung", "fuehrung"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Durchleuchten", "durchleuchten", "erleuchten"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Fördern_Sensiblisieren_und_Gedeihen", "foerdern", "fördern", "begrenzen", "sensibilisieren", "gedeihen", "verderben"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Überheblichkeit", "überheblich", "ueberheblichkeit", "ueberheblich", "überheblichkeit"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Polung_der_Liebe", "liebepolung"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Egoismus_vs_Altruismus", "egoismus", "altruismus", "egoist", "altruist"], [136]))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["kausal", "geltung", "genese"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Gleichheit", "gleich"], []))
    parameter_entries.append(ParameterEntry(["Eigenschaften_n", "eigenschaften", "eigenschaft", "konzept", "konzepte"], ["Überleben", "ueberleben"], []))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], [], [43, 54, 74, 95]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["um1"], [155]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["um2"], [156]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["um3"], [157]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["warum_Transzendentalie_=_Strukturgroesse_=_Charakter", "warumtranszendentaliezustrukturgroesseundcharakter"], [4, 5, 54, 165]))
    parameter_entries.append(ParameterEntry(["Inkrementieren", "inkrementieren"], ["warum_Transzendentalie_=_Komplexität_von_Michael_Commons", "warumtranszendentaliegleichkomplexitaet"], [5, 65, 166]))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Rahmen-Bedingungen", "rahmen"], [226]))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Motive_gleichförmige_Polygone", "motivgleichfoermig"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Struktur_gleichförmige_Polygone", "strukturgleichfoermig"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Motive_Sternpolygone", "motivstern"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Struktur_Sternpolygone", "strukturstern"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Motiv_Sternpolygon_gebrochen-rational", "motivgebrstern"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Struktur_Sternpolyon_gebrochen-rational", "strukgebrstern"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Motiv_gleichförmige_Polygone_gebrochen-rational", "motivgebrgleichf"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["Struktur_gleichförmige_Polygone_gebrochen-rational", "strukgebrgleichf"], []))
    parameter_entries.append(ParameterEntry(["Multiplikationen", "multiplikationen"], ["beschrieben"], []))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["Q", "q", "Siebzehn"], [431, 432, 433, 434, 437, 441, 442, 443, 445, 450, 467, 468, 469, 487, 488, 544, 570, 590, 616, 700]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AB", "ab", "Achtundzwanzig"], [583, 587]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["Z", "z", "Sechsundzwanzig"], [543]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AA", "aa", "Sechsundzwanzig"], [558, 559, 560]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["i", "I", "Neun"], [517, 565, 681]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["G", "g", "Sieben"], [518]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["J", "j", "Zehn"], [514]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["k", "K", "Elf"], [515, 577, 578, 705, 706, 707]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["E", "e", "Fünf"], [511]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["L", "l", "Zwölf"], [506]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AU", "au", "Siebenundvierzig"], [532]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AK", "ak", "Siebenunddreissig"], [531]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AE", "ae", "Einunddreissig"], [530, 612, 613]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AD", "ad", "Dreissig"], [529, 547, 614]))
    parameter_entries.append(ParameterEntry(["Universum", "universum", "transzendentalien", "strukturalien", "kugel", "kugeln", "ball", "baelle", "bälle"], ["Morphismen", "morphismus"], [727]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AC", "ac", "Neunundzwanzig"], [528, 586, 727]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["AT", "at", "Sechsundvierzig"], [568]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["W", "w", "Dreiundzwanzig"], [527, 567]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["Y", "y", "Fünfundzwanzig"], [507, 510]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["Kontinuen", "F", "f", "Sechs"], [508]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["F", "f", "Sechs", "Kontinuen"], [508]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["O", "o", "Fünfzehn"], [5]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["H", "h", "Acht"], [491]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["N", "n", "Vierzehn"], [492]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["M", "m", "Dreizehn"], [493, 744]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["T", "t", "Zwanzig"], [486, 571, 572]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["Religionen_Kraefte_Krieg_der_Sterne_Star_Wars"], [584, 623]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["P", "p", "Sechszehn", "Dimensionen", "Multiversum_sind_die_Dimensionen"], [435, 569, 605, 637, 663, 691]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["P5", "p5", "Sechszehn->Fünf"], [501]))
    parameter_entries.append(ParameterEntry(["Multiversum", "multiversum"], ["P5", "p5", "Sechszehn->Fünf"], [501]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["P", "p", "Sechszehn"], [435, 569, 605, 637, 663, 691]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["X", "x", "Vierundzwanzig"], [25, 55, 386, 436, 549, 554, 565, 566, 591, 618, 619, 681]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["S", "s", "Neunzehn"], [504, 575]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["R", "r", "Achtzehn"], [436, 451, 556, 618]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["A", "a", "Eins"], [446]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["B", "b", "Zwei"], [447]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["C", "c", "Drei"], [448]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Konservativismus", "konservativ"], [651, 652, 653, 654, 655, 656]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Meisterschaft", "Professioneller", "meister", "profi"], [596]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Management", "managen", "handhaben"], [658]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Evolution", "intelligent_Design"], [657]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Karriere", "karriere"], [595, 597, 712, 713, 714, 715]))
    parameter_entries.append(ParameterEntry(["Menschliches", "menschliches"], ["Eliten", "elite"], [585]))
    parameter_entries.append(ParameterEntry(["Kontinuum", "kontinuum"], ["D", "d", "Vier"], [449, 585]))
    var tag_names = List[String]()
    tag_names.append("galaxie")
    tag_names.append("gebrRat")
    tag_names.append("gleichfoermigesPolygon")
    tag_names.append("keinParaOdMetaP")
    tag_names.append("keinPolygon")
    tag_names.append("sternPolygon")
    tag_names.append("universum")
    return RetaContextSchema(
        language_aliases^, translation_domains^, parameters_main^,
        row_parameters^, output_parameters^, output_modes^,
        combination_parameters^, scopes^, parameter_entries^,
        tag_names^,
        SchemaModuleNames("i18n.words", "i18n.words", "i18n.words"),
    )
