#!/usr/bin/env python3
"""Generate the exact Python meta-column fraction contract.

The legacy owner uses ``OrderedSet`` when available and otherwise a normal
``set``.  Both expose iteration order to downstream generated-column logic.
For a reproducible Python-free runtime we freeze the CPython order under
``PYTHONHASHSEED=0`` together with hashes of the two source CSV files.
"""
from __future__ import annotations

import hashlib
import os
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REFERENCE_ROOT = ROOT / "python_reference"
CSV_DIR = REFERENCE_ROOT / "csv"
OUTPUT = ROOT / "assets" / "meta_columns_catalog.tsv"

if os.environ.get("PYTHONHASHSEED") != "0":
    raise SystemExit(
        "generate_meta_columns_catalog.py requires PYTHONHASHSEED=0 "
        "to freeze the legacy set iteration order"
    )

sys.path.insert(0, str(REFERENCE_ROOT))

from reta_architecture import meta_columns  # noqa: E402


class _TableLimits:
    hoechsteZeile = {1024: 1024}


class _ReferenceMetaRuntime:
    def __init__(self) -> None:
        self.tables = _TableLimits()
        self.CSVsAlreadRead: dict[str, list[list[str]]] = {}
        self.BruecheUni: tuple[Fraction, ...] = ()
        self.BruecheGal: tuple[Fraction, ...] = ()
        self.BruecheEmo: tuple[Fraction, ...] = ()
        self.BruecheStrukGroesse: tuple[Fraction, ...] = ()

    def readConcatCSV_choseCsvFile(self, selection: object) -> str:
        filename = (
            "gebrochen-rational-galaxie.csv"
            if selection in (2, 3)
            else "gebrochen-rational-universum.csv"
        )
        return str(CSV_DIR / filename)


_ReferenceMetaRuntime.getAllBrueche = meta_columns.getAllBrueche
_ReferenceMetaRuntime.readOneCSVAndReturn = meta_columns.readOneCSVAndReturn
_ReferenceMetaRuntime.findAllBruecheAndTheirCombinations = (
    meta_columns.findAllBruecheAndTheirCombinations
)


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _fraction_fields(value: Fraction) -> tuple[str, str]:
    return str(value.numerator), str(value.denominator)


def build_rows() -> list[tuple[str, ...]]:
    runtime = _ReferenceMetaRuntime()
    combinations = runtime.findAllBruecheAndTheirCombinations()
    rows: list[tuple[str, ...]] = []

    for domain, filename, values in (
        ("universe", "gebrochen-rational-universum.csv", runtime.BruecheUni),
        ("galaxy", "gebrochen-rational-galaxie.csv", runtime.BruecheGal),
    ):
        source = CSV_DIR / filename
        rows.append(("source", domain, filename, _digest(source), str(len(values))))
        for order, value in enumerate(values):
            rows.append(("fraction", domain, str(order), *_fraction_fields(value)))

    for context in ("UniUni", "UniGal", "GalUni", "GalGal"):
        for polygon in ("stern", "gleichf"):
            for operation in ("mul", "div"):
                values = combinations[context][polygon][operation]
                for order, pair in enumerate(values):
                    first, second = pair
                    rows.append(
                        (
                            "combination",
                            context,
                            polygon,
                            operation,
                            str(order),
                            *_fraction_fields(first),
                            *_fraction_fields(second),
                        )
                    )
    return rows


def main() -> None:
    rows = build_rows()
    OUTPUT.write_text(
        "# generated by scripts/generate_meta_columns_catalog.py with PYTHONHASHSEED=0\n"
        + "".join("\t".join(row) + "\n" for row in rows),
        encoding="utf-8",
    )
    fractions = sum(row[0] == "fraction" for row in rows)
    combinations = sum(row[0] == "combination" for row in rows)
    print(
        f"wrote {fractions} fractions and {combinations} combinations "
        f"to {OUTPUT.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
