#!/usr/bin/env python3
"""Generate byte-exact native CLI help assets from the Python reference.

The generated text files are immutable runtime data.  Native Mojo executables
read them directly, so normal ``reta -h`` execution does not import or spawn
Python.  Regeneration remains explicit and verifies both language variants
against the bundled compatibility reference.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "python_reference"
ASSETS = ROOT / "assets"
CASES = {
    "reta_help_de.txt": ["-h"],
    "reta_help_en.txt": ["-language=english", "-h"],
}


def reference_python() -> str:
    return os.environ.get("RETA_REFERENCE_PYTHON", sys.executable)


def render(arguments: list[str]) -> bytes:
    completed = subprocess.run(
        [reference_python(), "reta.py", *arguments],
        cwd=REFERENCE,
        env={**os.environ, "PYTHONHASHSEED": "0"},
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0 or completed.stderr:
        raise SystemExit(
            "reference help generation failed for "
            f"{arguments!r}: status={completed.returncode}, "
            f"stderr={completed.stderr.decode('utf-8', errors='replace')}"
        )
    return completed.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify checked-in assets without modifying them",
    )
    args = parser.parse_args()

    generated = {name: render(arguments) for name, arguments in CASES.items()}
    for name, payload in generated.items():
        if not payload.endswith(b"\n"):
            raise SystemExit(f"generated help asset has no trailing LF: {name}")
        destination = ASSETS / name
        if args.check:
            if not destination.is_file():
                raise SystemExit(f"missing generated help asset: {destination}")
            current = destination.read_bytes()
            if current != payload:
                with tempfile.NamedTemporaryFile(
                    prefix=name + ".", suffix=".generated", delete=False
                ) as temporary:
                    temporary.write(payload)
                    temporary_path = Path(temporary.name)
                raise SystemExit(
                    f"stale help asset: {destination}; generated bytes: "
                    f"{temporary_path}"
                )
        else:
            destination.write_bytes(payload)
        print(f"{name}: {len(payload)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
