#!/usr/bin/env python3
"""Generate the native reta_architecture package-export catalog.

The Python package ``reta_architecture.__init__`` is a pure re-export facade.
This generator freezes its import bindings and explicit ``__all__`` order into
an architecture-independent TSV consumed by Mojo at runtime.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ImportBinding:
    import_ordinal: int
    module: str
    imported_name: str
    public_name: str


def parse_facade(path: Path) -> tuple[list[ImportBinding], list[str]]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    bindings: list[ImportBinding] = []
    public_names: list[str] | None = None

    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            if node.level != 1 or not node.module:
                raise ValueError(
                    f"unsupported import in {path}:{node.lineno}: only relative module imports are allowed"
                )
            for alias in node.names:
                if alias.name == "*":
                    raise ValueError(f"star import is not supported in {path}:{node.lineno}")
                bindings.append(
                    ImportBinding(
                        len(bindings),
                        node.module,
                        alias.name,
                        alias.asname or alias.name,
                    )
                )
        elif isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            if public_names is not None:
                raise ValueError(f"multiple __all__ assignments in {path}")
            if not isinstance(node.value, (ast.List, ast.Tuple)):
                raise ValueError(f"non-literal __all__ in {path}:{node.lineno}")
            values: list[str] = []
            for element in node.value.elts:
                if not isinstance(element, ast.Constant) or not isinstance(element.value, str):
                    raise ValueError(f"non-string __all__ entry in {path}:{node.lineno}")
                values.append(element.value)
            public_names = values

    if public_names is None:
        raise ValueError(f"missing __all__ in {path}")

    by_public: dict[str, ImportBinding] = {}
    for binding in bindings:
        if binding.public_name in by_public:
            raise ValueError(f"duplicate imported public name: {binding.public_name}")
        by_public[binding.public_name] = binding

    duplicates = sorted({name for name in public_names if public_names.count(name) > 1})
    if duplicates:
        raise ValueError(f"duplicate __all__ entries: {', '.join(duplicates)}")
    missing = [name for name in public_names if name not in by_public]
    if missing:
        raise ValueError(f"__all__ names without import binding: {', '.join(missing)}")
    return bindings, public_names


def render_catalog(source: Path, bindings: list[ImportBinding], public_names: list[str]) -> str:
    by_public = {binding.public_name: binding for binding in bindings}
    public_set = set(public_names)
    source_digest = hashlib.sha256(source.read_bytes()).hexdigest()
    rows = [
        "# generated by tools/generate_architecture_exports.py",
        f"# source_sha256={source_digest}",
        "# all_ordinal\timport_ordinal\tmodule\timported_name\tpublic_name\tpublic",
    ]
    for all_ordinal, name in enumerate(public_names):
        binding = by_public[name]
        rows.append(
            f"{all_ordinal}\t{binding.import_ordinal}\t{binding.module}\t"
            f"{binding.imported_name}\t{binding.public_name}\t1"
        )
    for binding in bindings:
        if binding.public_name in public_set:
            continue
        rows.append(
            f"-1\t{binding.import_ordinal}\t{binding.module}\t"
            f"{binding.imported_name}\t{binding.public_name}\t0"
        )
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("python_reference/reta_architecture/__init__.py"),
    )
    parser.add_argument(
        "--output", type=Path, default=Path("assets/architecture_exports.tsv")
    )
    args = parser.parse_args()
    source = args.source.resolve()
    bindings, public_names = parse_facade(source)
    payload = render_catalog(source, bindings, public_names)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(payload, encoding="utf-8", newline="\n")
    print(f"generated={args.output}")
    print(f"imports={len(bindings)}")
    print(f"public_exports={len(public_names)}")
    print(f"modules={len({binding.module for binding in bindings})}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
